Add more tools.
douban/Kenshin pull request #9
Opened 2016-12-18 08:13 UTC by zzl0

2016-12-22 11:41 UTC, zzl0 commented
@camper42 @lianwenbo please review

2016-12-23 04:42 UTC, camper42 requested changes
rehash whisper 的部分我觉得没什么问题
就那两个 URL 改一下就成

2016-12-23 04:42 UTC, camper42 commented on setup.py
>      url='http://code.dapps.douban.com/Kenshin',
这两行的URL需要改一下

2016-12-23 10:19 UTC, camper42 requested changes

2016-12-23 10:19 UTC, camper42 commented on bin/kenshin-rehash.py
> +              'use kenshin-find-file.py to generate this file.')
这里缺个反括号Orz

2016-12-23 11:51 UTC, zzl0 commented on bin/kenshin-rehash.py
> +              'use kenshin-find-file.py to generate this file.')
thanks，你今天有没有做集成测试？

2016-12-23 12:24 UTC, camper42 commented
type whisper 时 rehash 报错 ` StringIO instance has no attribute 'startswith‘`
还在确认到底是哪里抛的这个异常

2016-12-23 13:18 UTC, zzl0 commented
@camper42 在 whisper_read_header 那里，异常时这个函数里面抛出来的，我明天测试下 whisper2kenshin 的逻辑，好久没有使用 whisper 的数据，这里我用错了。

2016-12-23 14:32 UTC, camper42 commented on bin/kenshin-rehash.py
> +              'use kenshin-find-file.py to generate this file.')
和线上代码做了diff，只试着跑了有变动的 kenshin-cache-query 和 kenshin-rehash 
你说的集成测试是指？

2016-12-24 01:30 UTC, zzl0 commented on bin/kenshin-rehash.py
> +              'use kenshin-find-file.py to generate this file.')
当做外部用户，按照 README 上的流程走一遍，部署起来 Kenshin 集群，测试 kenshin-cache-query、kenshin-rehash。

2016-12-24 09:08 UTC, zzl0 commented
@camper42 感谢 review，我今天做了下面两件事情，请重新 review，另外，你有时间的换也可以按照 README 中的步骤走一遍，看看有什么描述不清楚，或者遗漏的地方。

1. 我修改了下 README 中 Demo Cluster 的部署测试流程。https://github.com/douban/graphite-kenshin 
2. 同时也测试了 kenshin-rehash.py 对 whisper 的支持。（用于 whisper -> kenshin 的转换）。

也期待你给 kenshin-rehash.py 加进度条的改进。

2016-12-25 03:47 UTC, camper42 commented
一个是之前提到的 setup.py 中 code.dapps 的 URL 需要改一下
另一个想问一下删除 kenshin-add-metric 的原因是？

2016-12-25 04:04 UTC, zzl0 commented
> 一个是之前提到的 setup.py 中 code.dapps 的 URL 需要改一下
thx

> 另一个想问一下删除 kenshin-add-metric 的原因是？

和 kenshin-send-sero-metric.py 类似，而且这个只特定于 whisper ，所以删掉。

2016-12-25 04:56 UTC, camper42 commented
1. 从 whisper rehash 出现 `[merge error] /data/kenshin/storage/data/11/default/275.hs: list index out of range`
whisper 是我临时跑的，whisper 如果不是预先创建所有 archives 的话，会出现 archives 数量不同，导致这个报错？

2. rehash 实际上只支持通过 http 服务器获取数据？help 有些误导

2016-12-25 05:03 UTC, zzl0 commented
> 从 whisper rehash 出现 [merge error] /data/kenshin/storage/data/11/default/275.hs: list index out of range whisper 是我临时跑的，whisper 如果不是预先创建所有 archives 的话，会出现 archives 数量不同，导致这个报错？

这个是预期的，rehash 的时候需要保证 archive schema 一致。

> rehash 实际上只支持通过 http 服务器获取数据？help 有些误导

这个可以删掉

2016-12-25 05:07 UTC, camper42 commented
那没别的问题了，可以考虑后续让报错更友好一些，现在看这个报错还得分析一下才知道为什么

2016-12-25 05:21 UTC, zzl0 commented
> 那没别的问题了，可以考虑后续让报错更友好一些，现在看这个报错还得分析一下才知道为什么

已更新。也可以，之前的 whisper2kenshin 脚本是有比较细的检查，后来做 kenshin-rehash 简化去掉了，因为我觉得用处不大。你觉得有必要的话，也可以加一些类似的检查回来。

2016-12-25 05:35 UTC, camper42 approved these changes

2016-12-25 05:36 UTC, merged